project:
  type: website

website:
  title: "test_website2"
  navbar:
    title: false
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: More
        menu:
          - about.qmd
          - index.qmd

format:
  html:
    theme: simplex
    css: assets/styles.css
    toc: true
