project:
  type: website

website:
  title: "Quarto website sandbox"
  sidebar:
    contents: chapters/
    title: "Sidebar title"
    # logo: https://datasciencecampus.ons.gov.uk/wp-content/uploads/sites/10/2017/03/data-science-campus-logo-new.svg
    style: "floating"
    search: false

  page-footer:
    center: 
      - text: "Footer"
        href: footer.qmd

  navbar:
   title: <span style="font-size:150%;font-weight:bold;">Introduction to R</span>
   logo: assets/images/af_dsc.png
   background: white
   pinned: true
   #center: "---"
   #right:
   #  - href: index.qmd
   #    text: Home
   #  - about.qmd
   #  - text: More
   #    menu:
   #      - about.qmd
   #      - index.qmd

format:
  html:
    theme: 
      - simplex
      - assets/custom.scss
    #css: assets/styles.css
    grid:
      sidebar-width: 200px
      #body-width: 900px
      #margin-width: 300px
      #gutter-width: 1.5rem
    toc: true
