project:
  type: website

website:
  title: "test_website2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: simplex
    css: assets/styles.css
    toc: true
