project:
  type: website

website:
  title: "test_website2"
  navbar:
    title: false
    logo: https://datasciencecampus.ons.gov.uk/wp-content/uploads/sites/10/2017/03/data-science-campus-logo-new.svg
    background: secondary
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: More
        menu:
          - about.qmd
          - index.qmd

format:
  html:
    theme: simplex
    css: assets/styles.css
    toc: true
